# This file was generated by GoReleaser. DO NOT EDIT.
cask "gbx" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "0e41ddae8982a6da0c5ca42524156aa56ceb96497f9eb54bfbf66591bd15f0b5"
      url "https://github.com/deemson/gbx/releases/download/v#{version}/gbx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b72e6e079b7618b9e69e70ab052e469ed18ac84ea5f73b5bbb4c060ed9b685ca"
      url "https://github.com/deemson/gbx/releases/download/v#{version}/gbx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "736c90ad39fc74a6da08966d6efe0346c05d896f04910835678d2165be9c820e"
      url "https://github.com/deemson/gbx/releases/download/v#{version}/gbx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba91423eee9db60370c41d37aa82ce669b798b16b04f9a0ba028f796dba0011c"
      url "https://github.com/deemson/gbx/releases/download/v#{version}/gbx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gbx"
  desc "Manage your fleet of git repos with a pretty TUI"
  homepage "https://github.com/deemson/gbx"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "gbx"

  # No zap stanza required

end
