# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gbx < Formula
  desc "Manage your fleet of git repos with a pretty TUI"
  homepage "https://github.com/deemson/gbx"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deemson/gbx/releases/download/v0.2.0/gbx_0.2.0_darwin_amd64.tar.gz"
      sha256 "6204f065c84456a6ddabc2f3e572f325c2838b7ccbb0d87ccc6b356e8dfecb46"

      define_method(:install) do
        bin.install "gbx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deemson/gbx/releases/download/v0.2.0/gbx_0.2.0_darwin_arm64.tar.gz"
      sha256 "1babab3bebf3a5bfd1ba69fe54998ecb4f0d6a4f16082cd5e64d55d5addcf176"

      define_method(:install) do
        bin.install "gbx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deemson/gbx/releases/download/v0.2.0/gbx_0.2.0_linux_amd64.tar.gz"
      sha256 "75df786a75138f4d6683537b46980b6a392c891ec7386f7914b2076f7e65671c"
      define_method(:install) do
        bin.install "gbx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deemson/gbx/releases/download/v0.2.0/gbx_0.2.0_linux_arm64.tar.gz"
      sha256 "2ebf30a11ed7bacf6ed4629064f21272dc4ef686f634fadc3304ddd4f3171d8f"
      define_method(:install) do
        bin.install "gbx"
      end
    end
  end

  test do
    system "#{bin}/gbx", "--help"
  end
end
