# typed: strict
# frozen_string_literal: true

# This file is generated by deemson/shed release CI. DO NOT EDIT.
class Shed < Formula
  desc "Sync dotfiles between system paths and a local shed"
  homepage "https://github.com/deemson/shed"
  version "0.2.0"
  license "MIT"

  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/deemson/shed/releases/download/v0.2.0/shed-aarch64-apple-darwin.tar.gz"
    sha256 "41b8cc6229bb8e0cbe80302e66292f6cc2afadfcd96bf5f8a2ba83321f55ffb7"
  else
    url "https://github.com/deemson/shed/releases/download/v0.2.0/shed-x86_64-apple-darwin.tar.gz"
    sha256 "5837f99398177e11f6eafa088c6dc94d286f1361c27c7f463456ee005aa1fcfd"
  end

  def install
    bin.install "shed"
  end

  test do
    assert_match "shed #{version}", shell_output("#{bin}/shed --version")
  end
end
