# typed: strict
# frozen_string_literal: true

# This file is generated by deemson/shed release CI. DO NOT EDIT.
class Shed < Formula
  desc "Sync dotfiles between system paths and a local shed"
  homepage "https://github.com/deemson/shed"
  version "0.1.0"
  license "MIT"

  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/deemson/shed/releases/download/v0.1.0/shed-aarch64-apple-darwin.tar.gz"
    sha256 "5befef073a05c4348f3d561155ca72c9f00ad54d3784c07e2f2a9cdf15bd6a36"
  else
    url "https://github.com/deemson/shed/releases/download/v0.1.0/shed-x86_64-apple-darwin.tar.gz"
    sha256 "041d0815108c74ee98b6da7a978a5eeeb0cf66c815e87fd174bb575c635e5370"
  end

  def install
    bin.install "shed"
  end

  test do
    assert_match "shed #{version}", shell_output("#{bin}/shed --version")
  end
end
